---
sudo: true
language: python
services:
  - docker

jobs:
  include:
    - install: pip install pipenv && pipenv install && pipenv run pip install "ansible>=2.2,<2.3"
      script: make test
    - install: pip install pipenv && pipenv install && pipenv run pip install "ansible>=2.3,<2.4"
      script: make test
    - install: pip install pipenv && pipenv install && pipenv run pip install "ansible>=2.4,<2.5"
      script: make test
    - install: pip install pipenv && pipenv install && pipenv run pip install "ansible>=2.5"
      script: make test
